name: Create release on new tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    
    - name: Set up Python
      uses: actions/setup-python@v2
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    
    - name: Build release binaries
      run: pio run -e emontx-01 -e emontx-02 -e emontx-03
      env:
        MQTT_BROKER: ${{ secrets.MQTT_BROKER }}
        MQTT_PORT: ${{ secrets.MQTT_PORT }}
        MQTT_USERNAME: ${{ secrets.MQTT_USERNAME }}
        MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD }}

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: .pio/build/**/*_v${{ github.ref_name }}.hex
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
